export const ERRORS = {
    GEMINI_QUOTA: "GEMINI_QUOTA_EXCEEDED",

    GEMINI_BUSY: "GEMINI_UNAVAILABLE",

    BATAM_POS: "BATAM_POS_NOT_READY",

    TRIBUN: "TRIBUN_BATAM_NOT_READY",

    SCRAPER_FAILED: "SCRAPER_FAILED",

    INVALID_SOURCE: "INVALID_SOURCE"
}